### ISSUE TITLE
Cmake warning in building pointcloud_preprocessor

### ISSUE THREAD

**Issue by fred-apex-ai** [tier4/Pilot.Auto#129]
`pointcloud_preprocessor` builds but issues a warning. 

```
--- stderr: pointcloud_preprocessor 
CMake Warning (dev) at CMakeLists.txt:18 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PCL_ROOT is set to:

    /usr

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

There are other packages that rely on `PCL` and don't have this warning, so we should be able to get rid of it

**Comment by jilaada** [comment]
@fred-apex-ai During the linting of pointcloud_preprocessor I thought I would just try to resolve this issue as well, please take a look: https://github.com/tier4/Pilot.Auto/pull/180

**Comment by jilaada** [comment]
I think we can close this issue now that #180 is merged with this fixes.
