### ISSUE TITLE
ROI generation for traffic light recognition

### ISSUE THREAD

**Issue by VRichardJP** [tier4/Pilot.Auto#59]
Hi

I am trying to figure out how to add a camera for traffic light recognition in pilot.auto 0.5.1.
I can't manage to generate ROIs for the traffic light because I don't have the camera<->map transform for my camera images.

The file here:
https://github.com/tier4/autoware_launcher.iv.universe/blob/master/sensing_launch/data/traffic_light_camera.yaml

looks like a calibration for the camera. It looks similar to the calibration file in autoware.ai, except there is a 3x4 'projection_matrix' which does not exist in .ai calibration files. What does this matrix correspond to?

Is there any tool to generate this calibration file? or is it possible to convert calibration from .ai to pilot.auto?

Thanks

**Comment by yucedagonurcan** [comment]
Hello,

- It is basically camera info file that you can use it for many thing but especially for 3D-2D projection. But you need a node to convert/publish it to a **/camera_info**  (`sensor_msgs/CameraInfo)`  topic. 

- You can create camera_info topic with this small script from a .yaml file that looks like what you linked in your post: 
   - https://answers.ros.org/question/33929/camera-calibration-parser-in-python/?answer=38386#post-id-38386

- You can read more about Projection Matrix(3x4) and difference of it with the CameraMatrix(3x3):
   - http://docs.ros.org/en/api/sensor_msgs/html/msg/CameraInfo.html

Have a great day.

**Comment by VRichardJP** [comment]
Thank you very much
